//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChi
    {
        public int MaDC { get; set; }
        public int MaKH { get; set; }
        public string TinhThanhPho { get; set; }
        public string QuanHuyen { get; set; }
        public string PhuongXa { get; set; }
        public string DiaChiCuThe { get; set; }
        public bool LaDiaChiMacDinh { get; set; }
        public System.DateTime NgayThem { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
    }
}
