//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int MaDonHang { get; set; }
        public int MaKH { get; set; }
        public System.DateTime NgayDat { get; set; }
        public decimal TongTien { get; set; }
        public decimal PhiShip { get; set; }
        public string TrangThaiDonHang { get; set; }
        public string GhiChu { get; set; }
        public string DiaChi_Full { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}
