//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_PHONGGYM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QL_PHONGGYMEntities : DbContext
    {
        public QL_PHONGGYMEntities()
            : base("name=QL_PHONGGYMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietGioHang> ChiTietGioHangs { get; set; }
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<ChuyenMon> ChuyenMons { get; set; }
        public virtual DbSet<DangKyGoiTap> DangKyGoiTaps { get; set; }
        public virtual DbSet<DangKyLop> DangKyLops { get; set; }
        public virtual DbSet<DangKyPT> DangKyPTs { get; set; }
        public virtual DbSet<DiaChi> DiaChis { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GoiTap> GoiTaps { get; set; }
        public virtual DbSet<HINHANH> HINHANHs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LichLop> LichLops { get; set; }
        public virtual DbSet<LichTapPT> LichTapPTs { get; set; }
        public virtual DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public virtual DbSet<LoaiSanPham> LoaiSanPhams { get; set; }
        public virtual DbSet<LopHoc> LopHocs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    
        public virtual int sp_DangKyLop_KiemTra(Nullable<int> maKH, Nullable<int> maLop, ObjectParameter maDKLop)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKyLop_KiemTra", maKHParameter, maLopParameter, maDKLop);
        }
    
        public virtual int sp_GanChuyenMonChoNhanVien(Nullable<int> maNV, Nullable<int> maCM)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maCMParameter = maCM.HasValue ?
                new ObjectParameter("MaCM", maCM) :
                new ObjectParameter("MaCM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GanChuyenMonChoNhanVien", maNVParameter, maCMParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_HinhAnh_Sua(Nullable<int> maHinh, Nullable<int> maSP, string url, Nullable<bool> isMain)
        {
            var maHinhParameter = maHinh.HasValue ?
                new ObjectParameter("MaHinh", maHinh) :
                new ObjectParameter("MaHinh", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var isMainParameter = isMain.HasValue ?
                new ObjectParameter("IsMain", isMain) :
                new ObjectParameter("IsMain", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_HinhAnh_Sua", maHinhParameter, maSPParameter, urlParameter, isMainParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_HinhAnh_Them(Nullable<int> maSP, string url, Nullable<bool> isMain)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var urlParameter = url != null ?
                new ObjectParameter("Url", url) :
                new ObjectParameter("Url", typeof(string));
    
            var isMainParameter = isMain.HasValue ?
                new ObjectParameter("IsMain", isMain) :
                new ObjectParameter("IsMain", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_HinhAnh_Them", maSPParameter, urlParameter, isMainParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_HinhAnh_Xoa(Nullable<int> maHinh)
        {
            var maHinhParameter = maHinh.HasValue ?
                new ObjectParameter("MaHinh", maHinh) :
                new ObjectParameter("MaHinh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_HinhAnh_Xoa", maHinhParameter);
        }
    
        public virtual int sp_KhachHangDangKy(string tenKH, string gioiTinh, Nullable<System.DateTime> ngaySinh, string sDT, string email, string tenDangNhap, string matKhau)
        {
            var tenKHParameter = tenKH != null ?
                new ObjectParameter("TenKH", tenKH) :
                new ObjectParameter("TenKH", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_KhachHangDangKy", tenKHParameter, gioiTinhParameter, ngaySinhParameter, sDTParameter, emailParameter, tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual ObjectResult<sp_KhachHangLogin_Result> sp_KhachHangLogin(string tenDangNhap, string matKhau)
        {
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_KhachHangLogin_Result>("sp_KhachHangLogin", tenDangNhapParameter, matKhauParameter);
        }
    
        public virtual int sp_SuaChuyenMon(Nullable<int> maCM, string tenChuyenMon, string moTa)
        {
            var maCMParameter = maCM.HasValue ?
                new ObjectParameter("MaCM", maCM) :
                new ObjectParameter("MaCM", typeof(int));
    
            var tenChuyenMonParameter = tenChuyenMon != null ?
                new ObjectParameter("TenChuyenMon", tenChuyenMon) :
                new ObjectParameter("TenChuyenMon", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaChuyenMon", maCMParameter, tenChuyenMonParameter, moTaParameter);
        }
    
        public virtual ObjectResult<string> sp_SuaGoiTap(Nullable<int> maGoiTap, string tenGoi, Nullable<int> thoiHan, Nullable<decimal> gia, string moTa)
        {
            var maGoiTapParameter = maGoiTap.HasValue ?
                new ObjectParameter("MaGoiTap", maGoiTap) :
                new ObjectParameter("MaGoiTap", typeof(int));
    
            var tenGoiParameter = tenGoi != null ?
                new ObjectParameter("TenGoi", tenGoi) :
                new ObjectParameter("TenGoi", typeof(string));
    
            var thoiHanParameter = thoiHan.HasValue ?
                new ObjectParameter("ThoiHan", thoiHan) :
                new ObjectParameter("ThoiHan", typeof(int));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(decimal));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_SuaGoiTap", maGoiTapParameter, tenGoiParameter, thoiHanParameter, giaParameter, moTaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_SuaLoaiSanPham(Nullable<int> maLoaiSP, string tenLoaiSP)
        {
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            var tenLoaiSPParameter = tenLoaiSP != null ?
                new ObjectParameter("TenLoaiSP", tenLoaiSP) :
                new ObjectParameter("TenLoaiSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_SuaLoaiSanPham", maLoaiSPParameter, tenLoaiSPParameter);
        }
    
        public virtual int sp_SuaLopHoc(Nullable<int> maLop, string tenLop, Nullable<int> maCM, Nullable<decimal> hocPhi, Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc, Nullable<int> soBuoi, Nullable<int> siSoToiDa, Nullable<int> maNV, Nullable<System.TimeSpan> gioBatDau, Nullable<System.TimeSpan> gioKetThuc)
        {
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("TenLop", tenLop) :
                new ObjectParameter("TenLop", typeof(string));
    
            var maCMParameter = maCM.HasValue ?
                new ObjectParameter("MaCM", maCM) :
                new ObjectParameter("MaCM", typeof(int));
    
            var hocPhiParameter = hocPhi.HasValue ?
                new ObjectParameter("HocPhi", hocPhi) :
                new ObjectParameter("HocPhi", typeof(decimal));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            var soBuoiParameter = soBuoi.HasValue ?
                new ObjectParameter("SoBuoi", soBuoi) :
                new ObjectParameter("SoBuoi", typeof(int));
    
            var siSoToiDaParameter = siSoToiDa.HasValue ?
                new ObjectParameter("SiSoToiDa", siSoToiDa) :
                new ObjectParameter("SiSoToiDa", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var gioBatDauParameter = gioBatDau.HasValue ?
                new ObjectParameter("GioBatDau", gioBatDau) :
                new ObjectParameter("GioBatDau", typeof(System.TimeSpan));
    
            var gioKetThucParameter = gioKetThuc.HasValue ?
                new ObjectParameter("GioKetThuc", gioKetThuc) :
                new ObjectParameter("GioKetThuc", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_SuaLopHoc", maLopParameter, tenLopParameter, maCMParameter, hocPhiParameter, ngayBatDauParameter, ngayKetThucParameter, soBuoiParameter, siSoToiDaParameter, maNVParameter, gioBatDauParameter, gioKetThucParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_SuaSanPham(Nullable<int> maSP, string tenSP, Nullable<int> maLoaiSP, Nullable<decimal> donGia, Nullable<int> soLuongTon, Nullable<decimal> giaKhuyenMai, string hang, string xuatXu, string baoHanh, string moTaChung, string moTaChiTiet, Nullable<int> trangThai)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var giaKhuyenMaiParameter = giaKhuyenMai.HasValue ?
                new ObjectParameter("GiaKhuyenMai", giaKhuyenMai) :
                new ObjectParameter("GiaKhuyenMai", typeof(decimal));
    
            var hangParameter = hang != null ?
                new ObjectParameter("Hang", hang) :
                new ObjectParameter("Hang", typeof(string));
    
            var xuatXuParameter = xuatXu != null ?
                new ObjectParameter("XuatXu", xuatXu) :
                new ObjectParameter("XuatXu", typeof(string));
    
            var baoHanhParameter = baoHanh != null ?
                new ObjectParameter("BaoHanh", baoHanh) :
                new ObjectParameter("BaoHanh", typeof(string));
    
            var moTaChungParameter = moTaChung != null ?
                new ObjectParameter("MoTaChung", moTaChung) :
                new ObjectParameter("MoTaChung", typeof(string));
    
            var moTaChiTietParameter = moTaChiTiet != null ?
                new ObjectParameter("MoTaChiTiet", moTaChiTiet) :
                new ObjectParameter("MoTaChiTiet", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_SuaSanPham", maSPParameter, tenSPParameter, maLoaiSPParameter, donGiaParameter, soLuongTonParameter, giaKhuyenMaiParameter, hangParameter, xuatXuParameter, baoHanhParameter, moTaChungParameter, moTaChiTietParameter, trangThaiParameter);
        }
    
        public virtual int sp_ThemChucVu(string tenChucVu)
        {
            var tenChucVuParameter = tenChucVu != null ?
                new ObjectParameter("TenChucVu", tenChucVu) :
                new ObjectParameter("TenChucVu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChucVu", tenChucVuParameter);
        }
    
        public virtual int sp_ThemChuyenMon(string tenChuyenMon, string moTa)
        {
            var tenChuyenMonParameter = tenChuyenMon != null ?
                new ObjectParameter("TenChuyenMon", tenChuyenMon) :
                new ObjectParameter("TenChuyenMon", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChuyenMon", tenChuyenMonParameter, moTaParameter);
        }
    
        public virtual int sp_ThemGoiTap(string tenGoi, Nullable<int> thoiHan, Nullable<decimal> gia, string moTa)
        {
            var tenGoiParameter = tenGoi != null ?
                new ObjectParameter("TenGoi", tenGoi) :
                new ObjectParameter("TenGoi", typeof(string));
    
            var thoiHanParameter = thoiHan.HasValue ?
                new ObjectParameter("ThoiHan", thoiHan) :
                new ObjectParameter("ThoiHan", typeof(int));
    
            var giaParameter = gia.HasValue ?
                new ObjectParameter("Gia", gia) :
                new ObjectParameter("Gia", typeof(decimal));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemGoiTap", tenGoiParameter, thoiHanParameter, giaParameter, moTaParameter);
        }
    
        public virtual int sp_ThemLichLop(Nullable<int> maLop, Nullable<int> maNV, Nullable<System.DateTime> ngayHoc, Nullable<System.TimeSpan> gioBatDau, Nullable<System.TimeSpan> gioKetThuc)
        {
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var ngayHocParameter = ngayHoc.HasValue ?
                new ObjectParameter("NgayHoc", ngayHoc) :
                new ObjectParameter("NgayHoc", typeof(System.DateTime));
    
            var gioBatDauParameter = gioBatDau.HasValue ?
                new ObjectParameter("GioBatDau", gioBatDau) :
                new ObjectParameter("GioBatDau", typeof(System.TimeSpan));
    
            var gioKetThucParameter = gioKetThuc.HasValue ?
                new ObjectParameter("GioKetThuc", gioKetThuc) :
                new ObjectParameter("GioKetThuc", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLichLop", maLopParameter, maNVParameter, ngayHocParameter, gioBatDauParameter, gioKetThucParameter);
        }
    
        public virtual int sp_ThemLichTapPT(Nullable<int> maDKPT, Nullable<System.DateTime> ngayTap, Nullable<System.TimeSpan> gioBatDau, Nullable<System.TimeSpan> gioKetThuc, string trangThai)
        {
            var maDKPTParameter = maDKPT.HasValue ?
                new ObjectParameter("MaDKPT", maDKPT) :
                new ObjectParameter("MaDKPT", typeof(int));
    
            var ngayTapParameter = ngayTap.HasValue ?
                new ObjectParameter("NgayTap", ngayTap) :
                new ObjectParameter("NgayTap", typeof(System.DateTime));
    
            var gioBatDauParameter = gioBatDau.HasValue ?
                new ObjectParameter("GioBatDau", gioBatDau) :
                new ObjectParameter("GioBatDau", typeof(System.TimeSpan));
    
            var gioKetThucParameter = gioKetThuc.HasValue ?
                new ObjectParameter("GioKetThuc", gioKetThuc) :
                new ObjectParameter("GioKetThuc", typeof(System.TimeSpan));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLichTapPT", maDKPTParameter, ngayTapParameter, gioBatDauParameter, gioKetThucParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_ThemLoaiSanPham(string tenLoaiSP)
        {
            var tenLoaiSPParameter = tenLoaiSP != null ?
                new ObjectParameter("TenLoaiSP", tenLoaiSP) :
                new ObjectParameter("TenLoaiSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_ThemLoaiSanPham", tenLoaiSPParameter);
        }
    
        public virtual int sp_ThemLopHocVaLich(string tenLop, Nullable<int> maCM, Nullable<decimal> hocPhi, Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc, Nullable<int> siSoToiDa, Nullable<int> maNV, Nullable<System.TimeSpan> gioBatDau, Nullable<System.TimeSpan> gioKetThuc)
        {
            var tenLopParameter = tenLop != null ?
                new ObjectParameter("TenLop", tenLop) :
                new ObjectParameter("TenLop", typeof(string));
    
            var maCMParameter = maCM.HasValue ?
                new ObjectParameter("MaCM", maCM) :
                new ObjectParameter("MaCM", typeof(int));
    
            var hocPhiParameter = hocPhi.HasValue ?
                new ObjectParameter("HocPhi", hocPhi) :
                new ObjectParameter("HocPhi", typeof(decimal));
    
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("NgayBatDau", ngayBatDau) :
                new ObjectParameter("NgayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("NgayKetThuc", ngayKetThuc) :
                new ObjectParameter("NgayKetThuc", typeof(System.DateTime));
    
            var siSoToiDaParameter = siSoToiDa.HasValue ?
                new ObjectParameter("SiSoToiDa", siSoToiDa) :
                new ObjectParameter("SiSoToiDa", typeof(int));
    
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var gioBatDauParameter = gioBatDau.HasValue ?
                new ObjectParameter("GioBatDau", gioBatDau) :
                new ObjectParameter("GioBatDau", typeof(System.TimeSpan));
    
            var gioKetThucParameter = gioKetThuc.HasValue ?
                new ObjectParameter("GioKetThuc", gioKetThuc) :
                new ObjectParameter("GioKetThuc", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLopHocVaLich", tenLopParameter, maCMParameter, hocPhiParameter, ngayBatDauParameter, ngayKetThucParameter, siSoToiDaParameter, maNVParameter, gioBatDauParameter, gioKetThucParameter);
        }
    
        public virtual int sp_ThemNhanVien(Nullable<int> maChucVu, string tenDangNhap, string matKhau, string gioiTinh, string tenNV, string sDT, Nullable<System.DateTime> ngaySinh)
        {
            var maChucVuParameter = maChucVu.HasValue ?
                new ObjectParameter("MaChucVu", maChucVu) :
                new ObjectParameter("MaChucVu", typeof(int));
    
            var tenDangNhapParameter = tenDangNhap != null ?
                new ObjectParameter("TenDangNhap", tenDangNhap) :
                new ObjectParameter("TenDangNhap", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var tenNVParameter = tenNV != null ?
                new ObjectParameter("TenNV", tenNV) :
                new ObjectParameter("TenNV", typeof(string));
    
            var sDTParameter = sDT != null ?
                new ObjectParameter("SDT", sDT) :
                new ObjectParameter("SDT", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemNhanVien", maChucVuParameter, tenDangNhapParameter, matKhauParameter, gioiTinhParameter, tenNVParameter, sDTParameter, ngaySinhParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_ThemSanPham(string tenSP, Nullable<int> maLoaiSP, Nullable<decimal> donGia, Nullable<int> soLuongTon, Nullable<decimal> giaKhuyenMai, string hang, string xuatXu, string baoHanh, string moTaChung, string moTaChiTiet)
        {
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var maLoaiSPParameter = maLoaiSP.HasValue ?
                new ObjectParameter("MaLoaiSP", maLoaiSP) :
                new ObjectParameter("MaLoaiSP", typeof(int));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongTonParameter = soLuongTon.HasValue ?
                new ObjectParameter("SoLuongTon", soLuongTon) :
                new ObjectParameter("SoLuongTon", typeof(int));
    
            var giaKhuyenMaiParameter = giaKhuyenMai.HasValue ?
                new ObjectParameter("GiaKhuyenMai", giaKhuyenMai) :
                new ObjectParameter("GiaKhuyenMai", typeof(decimal));
    
            var hangParameter = hang != null ?
                new ObjectParameter("Hang", hang) :
                new ObjectParameter("Hang", typeof(string));
    
            var xuatXuParameter = xuatXu != null ?
                new ObjectParameter("XuatXu", xuatXu) :
                new ObjectParameter("XuatXu", typeof(string));
    
            var baoHanhParameter = baoHanh != null ?
                new ObjectParameter("BaoHanh", baoHanh) :
                new ObjectParameter("BaoHanh", typeof(string));
    
            var moTaChungParameter = moTaChung != null ?
                new ObjectParameter("MoTaChung", moTaChung) :
                new ObjectParameter("MoTaChung", typeof(string));
    
            var moTaChiTietParameter = moTaChiTiet != null ?
                new ObjectParameter("MoTaChiTiet", moTaChiTiet) :
                new ObjectParameter("MoTaChiTiet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_ThemSanPham", tenSPParameter, maLoaiSPParameter, donGiaParameter, soLuongTonParameter, giaKhuyenMaiParameter, hangParameter, xuatXuParameter, baoHanhParameter, moTaChungParameter, moTaChiTietParameter);
        }
    
        public virtual int sp_ThemVaoGioHang(Nullable<int> maKH, Nullable<int> maSP, Nullable<int> soLuong)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemVaoGioHang", maKHParameter, maSPParameter, soLuongParameter);
        }
    
        public virtual int sp_UpdateTrangThaiLichLop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateTrangThaiLichLop");
        }
    
        public virtual int sp_XoaChucVu(Nullable<int> maChucVu)
        {
            var maChucVuParameter = maChucVu.HasValue ?
                new ObjectParameter("MaChucVu", maChucVu) :
                new ObjectParameter("MaChucVu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChucVu", maChucVuParameter);
        }
    
        public virtual int sp_XoaChuyenMon(Nullable<int> maCM)
        {
            var maCMParameter = maCM.HasValue ?
                new ObjectParameter("MaCM", maCM) :
                new ObjectParameter("MaCM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaChuyenMon", maCMParameter);
        }
    
        public virtual int sp_XoaNhanVien(Nullable<int> maNV)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanVien", maNVParameter);
        }
    
        public virtual int sp_XoaNhanVienChuyenMon(Nullable<int> maNV, Nullable<int> maCM)
        {
            var maNVParameter = maNV.HasValue ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(int));
    
            var maCMParameter = maCM.HasValue ?
                new ObjectParameter("MaCM", maCM) :
                new ObjectParameter("MaCM", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaNhanVienChuyenMon", maNVParameter, maCMParameter);
        }
    
        public virtual int sp_XoaSanPham(Nullable<int> maSP)
        {
            var maSPParameter = maSP.HasValue ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaSanPham", maSPParameter);
        }
    
        public virtual int XoaLichVaLop(Nullable<int> maLop)
        {
            var maLopParameter = maLop.HasValue ?
                new ObjectParameter("MaLop", maLop) :
                new ObjectParameter("MaLop", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaLichVaLop", maLopParameter);
        }
    }
}
